apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  REDIS_HOST: "redis.default.svc.cluster.local"
  POSTGRES_HOST: "postgres.default.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "votes"
